### ISSUE TITLE
Do not check for Requires.private unless --static requested

### ISSUE THREAD

**Issue by ignatenkobrain** [pkgconf/pkgconf#126]
There was bug in Fedora in libselinux package which has `libpcre` in `Requires.private`. so libpcre.pc didn't exist on my system and when I was asking for `pkg-config --cflags libpcre` it was saying that `libpcre.pc` doesn't exist.. But pkgconf should not care because I didn't ask for static build.

**Comment by kaniini** [comment]
This is intentional.

In almost all cases, headers belonging to `Requires.private` are referenced indirectly.  So we need to ensure the dependency is satisfied to compile.

The only case where `Requires` and `Requires.private` should be differently handled is linking, which pkgconf correctly follows.

**Comment by ignatenkobrain** [comment]
@kaniini but there is `Cflags.private` where people should set their private includedirs..!

**Comment by tonytheodore** [comment]
@ignatenkobrain, `Cflags.private` isn't available in `pkg-config`.

**Comment by kaniini** [comment]
`Cflags.private` isn't about dependency management either, it's to provide things like `-DCOMPILE_STATIC` for example.
