### ISSUE TITLE
Why do `PKG_CONFIG_SYSTEM_LIBRARY_PATH`/`PKG_CONFIG_SYSTEM_INCLUDE_PATH` not respect `PKG_CONFIG_SYSROOT_DIR`?

### ISSUE THREAD

**Issue by mattst88** [pkgconf/pkgconf#264]
````sh
% pwd
/home/mattst88/projects/pkgconf
% PKG_CONFIG_PATH=$(pwd)/tests/lib1/ pkgconf --libs foo                      
-L/test/lib -lfoo 
````

Setting `PKG_CONFIG_SYSROOT_DIR=/test` doesn't affect the library path:

% PKG_CONFIG_PATH=$(pwd)/tests/lib1/ PKG_CONFIG_SYSROOT_DIR=/test pkgconf --libs foo
-L/test/lib -lfoo 
````

Setting `PKG_CONFIG_SYSTEM_LIBRARY_PATH=/test/lib` drops the library path:
````
% PKG_CONFIG_PATH=$(pwd)/tests/lib1/ PKG_CONFIG_SYSTEM_LIBRARY_PATH=/test/lib pkgconf --libs foo
-lfoo 
````

Shouldn't `PKG_CONFIG_SYSROOT_DIR=/test` cause pkgconf to drop -L/test/lib? That is, shouldn't `PKG_CONFIG_SYSTEM_LIBRARY_PATH` and `PKG_CONFIG_SYSTEM_INCLUDE_PATH` default to `${PKG_CONFIG_SYSROOT_DIR}/...`?

**Comment by kaniini** [comment]
The short answer is that instead of using these env variables, I recommend setting up a cross-personality file, pkgconf-personality(5) manpage will explain how to do it.

The longer answer is that these env variables have nothing to do with sysroot and inform pkgconf about how the toolchain works from the perspective of being outside the sysroot, so setting a sysroot cannot be allowed to influence them.
