### ISSUE TITLE
--modversion should accept multiple arguments when it's the same package

### ISSUE THREAD

**Issue by ptrcnull** [pkgconf/pkgconf#310]
currently, the following command will fail on pkgconf 2.0:
```
$ pkg-config --modversion dbus-1 'dbus-1 >= 1.6'
pkgconf: --modversion requested with multiple packages, output would be ambiguous
```

while it might be a bit redundant to do so in this case, the output would not be ambiguous, and unfortunately there's [prior art][1]

furthermore, with the check in place, there doesn't seem to be a way to query a package with both an upper and lower version bound; it didn't really work on pkgconf 1.x either, but it seems to work with pkg-config, so maybe it's worth looking into as well:
```
root@86a8a87bcfe7:/# pkg-config --modversion 'dbus-1 >= 1.6'
1.12.16
root@86a8a87bcfe7:/# pkg-config --modversion 'dbus-1 >= 1.6' 'dbus-1 < 1.10'
Requested 'dbus-1 < 1.10' but version of dbus is 1.12.16
root@86a8a87bcfe7:/# pkg-config --modversion 'dbus-1 >= 1.6' 'dbus-1 < 1.15'
1.12.16
1.12.16
```

[1]: https://github.com/rust-lang/pkg-config-rs/issues/150

**Comment by nirbheek** [comment]
This seems like completely unnecessary breakage. According to the release notes, this is an error because it's ambiguous. But the output is not ambiguous at all. The versions are printed in the order of the arguments:

```
$ pkg-config --modversion sqlite3 zlib
3.39.5
1.2.11
```

IMO this change should be completely reverted. There is no good reason for diverge from pkg-config in this case.

**Comment by Polynomial-C** [comment]
Unfortunately with commit a97b75ab2c1d031982c35a4886102413e4ec8eee being reverted, `pkgconf-2.0.0` only returns one version:
```
> pkgconf --modversion sqlite3 zlib
3.42.0
```
So there's some more breakage compared to pkgconfig.

**Comment by nekopsykose** [comment]
> Unfortunately with commit https://github.com/pkgconf/pkgconf/commit/a97b75ab2c1d031982c35a4886102413e4ec8eee being reverted, pkgconf-2.0.0 only returns one version:  

that was always like that, 1.9.5 behaves the same. 2.0 with that reverted is a safe upgrade

**Comment by Polynomial-C** [comment]
> > Unfortunately with commit [a97b75a](https://github.com/pkgconf/pkgconf/commit/a97b75ab2c1d031982c35a4886102413e4ec8eee) being reverted, pkgconf-2.0.0 only returns one version:
> 
> that was always like that, 1.9.5 behaves the same. 2.0 with that reverted is a safe upgrade
> 
> ```
> / # pkgconf --version
> 1.9.5
> / # pkgconf --modversion zlib libcurl
> 1.2.13
> ```

```
> pkgconf --version
1.8.1
> pkgconf --modversion sqlite3 zlib
3.42.0
1.2.13
```
I'd say someone broke 1.9.x versions then.

**Comment by Polynomial-C** [comment]
Trying to bisect this I always fail to compile pkgconf after commit 40638f24728a0685cba32d0254cdec3602c976ad got reverted.

**Comment by salihgerdan** [comment]
I ran across issues building a rust + gtk project on Windows due to this change, as msys2 has already packaged version 2.0.0. I had to work around it by downgrading to 1.8.0.
```
Warning: `"pkg-config" "--modversion" "glib-2.0" "glib-2.0 >= 2.66"` did not exit successfully: exit code: 1
error: failed to run custom build command for `glib-sys v0.17.2`
pkgconf: --modversion requested with multiple packages, output would be ambiguous
```
If anyone else also needs to work around this right now, you can do `pacman -U <url>` with one of the older packages you can find in https://packages.msys2.org/repos

I don't have any opinion if this change should happen or not, just here to provide a workaround if your stuff broke :)

**Comment by Ninpo** [comment]
> > > Unfortunately with commit [a97b75a](https://github.com/pkgconf/pkgconf/commit/a97b75ab2c1d031982c35a4886102413e4ec8eee) being reverted, pkgconf-2.0.0 only returns one version:
> > 
> > 
> > that was always like that, 1.9.5 behaves the same. 2.0 with that reverted is a safe upgrade
> > ```
> > / # pkgconf --version
> > 1.9.5
> > / # pkgconf --modversion zlib libcurl
> > 1.2.13
> > ```
> 
> ```
> > pkgconf --version
> 1.8.1
> > pkgconf --modversion sqlite3 zlib
> 3.42.0
> 1.2.13
> ```
> 
> I'd say someone broke 1.9.x versions then.

No, it seems 1.9 fixed incorrect usage of --modversion (passing different packages) which will break any script that uses it poorly however 2.0 broke legitimate usage where version constraints are passed because it simply counts passed argument and assumes that `pkg-config --modversion dbus-1 'dbus-1 >= 1.6'` is two different package arguments.

**Comment by kaniini** [comment]
We can revert the `--modversion` behavior back to the 1.8 behavior in 2.0.1 release.  However, there were arguments made for changing the behavior, e.g. in #304.

Some of the comments on this issue are unnecessarily aggressive in tone, and I would like to refer you to the Code of Conduct.

**Comment by kaniini** [comment]
On pkgconf 2.0.1, the `--modversion` behavior has been reverted back to the 1.8 behavior:

```
kaniini@phoebe build % ./pkgconf --with-path=/Users/kaniini/pkgconf/tests/lib1 'foo >= 1.2' bar --modversion
1.2.3
1.3
```

If you use `--verbose`, then you will get the module names prefixed before the version:

```
kaniini@phoebe build % ./pkgconf --with-path=/Users/kaniini/pkgconf/tests/lib1 'foo >= 1.2' bar --modversion --verbose
foo: 1.2.3
bar: 1.3
```

The new solver already solves the other issue, as it understands constraints, while the pkgconf 1.x solver only lazily evaluated constraints:

```
kaniini@phoebe build % ./pkgconf --with-path=/Users/kaniini/pkgconf/tests/lib1 'foo >= 1.2' 'foo < 1.2.4' --modversion
1.2.3
kaniini@phoebe build % ./pkgconf --with-path=/Users/kaniini/pkgconf/tests/lib1 'foo >= 1.2' 'foo < 1.2.2' --modversion
Package dependency requirement 'foo < 1.2.2' could not be satisfied.
Package 'foo' has version '1.2.3', required version is '< 1.2.2'
```

The lack of a second `foo` version in the above example is due to the second `foo` dependency node being cancelled out by the solver.  This is not an area where there will be bug-compatibility with freedesktop pkg-config.

**Comment by kaniini** [comment]
> This is not an area where there will be bug-compatibility with freedesktop pkg-config.

Update: in order to ensure that the output matches user expectations, instead of iterating over the calculated DAG, we now walk the dependency resolution queue that acts as input to the solver.  This results in `--modversion` respecting constraint order, and thus matches Freedesktop pkg-config behavior for free.

**Comment by eli-schwartz** [comment]
There's a weird edge case here introduced by commit f49029c681653044d19450f6c278bf54543d0d18 (cli: ensure --modversion is output is printed in dependency queue order):
https://github.com/pkgconf/pkgconf/blob/6a84d70439f03815080a3805fb10c81ffc8eece8/cli/main.c#L309-L310

This compares non-equal when looking up a package libfoo using libfoo-uninstalled.pc support. pkg->id is libfoo-uninstalled, but query_node->package is libfoo. So we end up skipping the modversion entirely here -- even when just one package is requested. :P

Aside: the printed --verbose value would be "libfoo-uninstalled: 1.0" if that check were fixed.

**Comment by kaniini** [comment]
We can probably solve that by swapping the strncmp around.  I'll cut a 2.0.2 later today which does this.

**Comment by eli-schwartz** [comment]
Swapping the order of the strncmp or what? Because either way they aren't identical, so I don't think that will help. I think what's really needed is to resolve pkg->id to not include "-uninstalled" before doing the comparison.

**Comment by breavyn** [comment]
`strncmp` is problematic here to begin with, what if you were checking libev and libevdev?
