### ISSUE TITLE
Widespread issues with empty PKG_CONFIG

### ISSUE THREAD

**Issue by ismaell** [pkgconf/pkgconf#350]
Too many projects' `configure` scripts don't check for empty `PKG_CONFIG`, yet use the variable directly, resulting in weird error messages through the run, which often confuse users. It would be useful to either error-out or set `PKG_CONFIG=false`, so that calls result in a fail without bogus errors.

In order to support both scenarios, I propose the `PKG_PROG_PKG_CONFIG` macro:
* by default abort the configure script.
* take an extra (optional) argument to specify a custom action instead.

**Comment by eli-schwartz** [comment]
I think that this is a terrible proposal and the linked commit should be reverted and re-released.

It causes an immediate regression for the *common* use case of `pkg.m4`, which is to not use PKG_PROG_PKG_CONFIG at all, but use:

```m4
PKG_CHECK_MODULES([FOO], [foo], , [
    dnl fall back to probing the library itself
    AC_CHECK_HEADER([foo.h])
    AC_CHECK_LIB([foo]) 
])
```

All these existing, ***correctly written*** autoconf scripts, now become *invalid* as a result of this change. Making existing correctly-written projects break, is much much worse than permitting broken projects to remain broken.

Broken projects should simply fix their brokenness. In fact they aren't even "broken" at all, since "weird error messages through the run, which often confuse users" is still an error, and users are empowered to report a bug to the project in question.

**Comment by thesamesam** [comment]
Reverted in https://github.com/pkgconf/pkgconf/commit/ad0d8b3944cba18f8dba2e33780e4196e1305934.

@kaniini is there a chance of a point release with this in? We can backport it but we need it fixed in dist tarballs too unfortunately.
